import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "@/components/Provider/SocketProvider";
import { Toaster } from "sonner";


const poppins = Poppins({ weight: ["500", "400", "300", "200", "100", "600", "800", "900"], subsets: ['latin'] })
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={poppins.className}>
        <SocketProvider>
          <Toaster richColors />
          {children}
        </SocketProvider>
      </body>
    </html>
  );
}
